/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 19-jun.-2023 22:01:52 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_EMPLEADO_USUARIO]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [EMPLEADO] DROP CONSTRAINT [FK_EMPLEADO_USUARIO]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[EMPLEADO]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [EMPLEADO]
GO

/* Create Tables */

CREATE TABLE [EMPLEADO]
(
	[EMP_NO] varchar(50) NOT NULL,
	[CI] varchar(50) NOT NULL,
	[EXP] varchar(50) NULL,
	[NOMBRE] varchar(100) NULL,
	[CARGO] varchar(100) NULL,
	[OFICINA_NO] varchar(100) NULL,
	[UNIDAD] varchar(100) NULL,
	[AREA_TRAB] varchar(50) NULL,
	[CELULAR] int NULL,
	[PROFESION] varchar(50) NULL,
	[USUARIO_NO] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [EMPLEADO] 
 ADD CONSTRAINT [PK_EMPLEADO]
	PRIMARY KEY CLUSTERED ([EMP_NO] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [EMPLEADO] ADD CONSTRAINT [FK_EMPLEADO_USUARIO]
	FOREIGN KEY ([USUARIO_NO]) REFERENCES [USUARIO] ([USUARIO_NO]) ON DELETE No Action ON UPDATE No Action
GO
