/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 19-jun.-2023 18:53:53 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PARTIDA_USUARIO]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [PARTIDA] DROP CONSTRAINT [FK_PARTIDA_USUARIO]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[PARTIDA]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [PARTIDA]
GO

/* Create Tables */

CREATE TABLE [PARTIDA]
(
	[PARTIDA_NO] varchar(50) NOT NULL,
	[NOMBRE] varchar(50) NULL,
	[PARTIDA] int NULL,
	[VIDA_UTIL] float NULL,
	[COEFICIENTE] float NULL,
	[DEPRECIACION] varchar(50) NULL,
	[ACTUALIZA] varchar(50) NULL,
	[USUARIO_NO] varchar(50) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [PARTIDA] 
 ADD CONSTRAINT [PK_PARTIDA]
	PRIMARY KEY CLUSTERED ([PARTIDA_NO] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [PARTIDA] ADD CONSTRAINT [FK_PARTIDA_USUARIO]
	FOREIGN KEY ([USUARIO_NO]) REFERENCES [USUARIO] ([USUARIO_NO]) ON DELETE No Action ON UPDATE No Action
GO
