/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 19-jun.-2023 14:11:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[USUARIO]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [USUARIO]
GO

/* Create Tables */

CREATE TABLE [USUARIO]
(
	[USUARIO_NO] varchar(50) NOT NULL,
	[CI] varchar(50) NULL,
	[NOMBRE] varchar(50) NULL,
	[PATERNO] varchar(50) NULL,
	[MATERNO] varchar(50) NULL,
	[CARGO] varchar(50) NULL,
	[PROFESION] varchar(50) NULL,
	[USUARIO] varchar(50) NOT NULL,
	[PASSWORD] int NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [USUARIO] 
 ADD CONSTRAINT [PK_USUARIO]
	PRIMARY KEY CLUSTERED ([USUARIO_NO] ASC)
GO
